mADD,kNormal,argRegMem8,argReg8
mADD,kNormal,argRegMem16,argReg16
mADD,kNormal,argReg8,argRegMem8
mADD,kNormal,argReg16,argRegMem16
mADD,kNormal,argRegAL,argImm8
mADD,kNormal,argRegAX,argImm16
mPUSH,kNormal,argRegES,argNone
mPOP,kNormal,argRegES,argNone
mOR,kNormal,argRegMem8,argReg8
mOR,kNormal,argRegMem16,argReg16
mOR,kNormal,argReg8,argRegMem8
mOR,kNormal,argReg16,argRegMem16
mOR,kNormal,argRegAL,argImm8
mOR,kNormal,argRegAX,argImm16
mPUSH,kNormal,argRegCS,argNone
0,kNormal,argNone,argNone
mADC,kNormal,argRegMem8,argReg8
mADC,kNormal,argRegMem16,argReg16
mADC,kNormal,argReg8,argRegMem8
mADC,kNormal,argReg16,argRegMem16
mADC,kNormal,argRegAL,argImm8
mADC,kNormal,argRegAX,argImm16
mPUSH,kNormal,argRegSS,argNone
mPOP,kNormal,argRegSS,argNone
mSBB,kNormal,argRegMem8,argReg8
mSBB,kNormal,argRegMem16,argReg16
mSBB,kNormal,argReg8,argRegMem8
mSBB,kNormal,argReg16,argRegMem16
mSBB,kNormal,argRegAL,argImm8
mSBB,kNormal,argRegAX,argImm16
mPUSH,kNormal,argRegDS,argNone
mPOP,kNormal,argRegDS,argNone
mAND,kNormal,argRegMem8,argReg8
mAND,kNormal,argRegMem16,argReg16
mAND,kNormal,argReg8,argRegMem8
mAND,kNormal,argReg16,argRegMem16
mAND,kNormal,argRegAL,argImm8
mAND,kNormal,argRegAX,argImm16
mSEGES,kPrefix,argNone,argNone
mDAA,kNormal,argNone,argNone
mSUB,kNormal,argRegMem8,argReg8
mSUB,kNormal,argRegMem16,argReg16
mSUB,kNormal,argReg8,argRegMem8
mSUB,kNormal,argReg16,argRegMem16
mSUB,kNormal,argRegAL,argImm8
mSUB,kNormal,argRegAX,argImm16
mSEGCS,kPrefix,argNone,argNone
mDAS,kNormal,argNone,argNone
mXOR,kNormal,argRegMem8,argReg8
mXOR,kNormal,argRegMem16,argReg16
mXOR,kNormal,argReg8,argRegMem8
mXOR,kNormal,argReg16,argRegMem16
mXOR,kNormal,argRegAL,argImm8
mXOR,kNormal,argRegAX,argImm16
mSEGSS,kPrefix,argNone,argNone
mAAA,kNormal,argNone,argNone
mCMP,kNormal,argRegMem8,argReg8
mCMP,kNormal,argRegMem16,argReg16
mCMP,kNormal,argReg8,argRegMem8
mCMP,kNormal,argReg16,argRegMem16
mCMP,kNormal,argRegAL,argImm8
mCMP,kNormal,argRegAX,argImm16
mSEGDS,kPrefix,argNone,argNone
mAAS,kNormal,argNone,argNone
mINC,kNormal,argRegAX,argNone
mINC,kNormal,argRegCX,argNone
mINC,kNormal,argRegDX,argNone
mINC,kNormal,argRegBX,argNone
mINC,kNormal,argRegSP,argNone
mINC,kNormal,argRegBP,argNone
mINC,kNormal,argRegSI,argNone
mINC,kNormal,argRegDI,argNone
mDEC,kNormal,argRegAX,argNone
mDEC,kNormal,argRegCX,argNone
mDEC,kNormal,argRegDX,argNone
mDEC,kNormal,argRegBX,argNone
mDEC,kNormal,argRegSP,argNone
mDEC,kNormal,argRegBP,argNone
mDEC,kNormal,argRegSI,argNone
mDEC,kNormal,argRegDI,argNone
mPUSH,kNormal,argRegAX,argNone
mPUSH,kNormal,argRegCX,argNone
mPUSH,kNormal,argRegDX,argNone
mPUSH,kNormal,argRegBX,argNone
mPUSH,kNormal,argRegSP,argNone
mPUSH,kNormal,argRegBP,argNone
mPUSH,kNormal,argRegSI,argNone
mPUSH,kNormal,argRegDI,argNone
mPOP,kNormal,argRegAX,argNone
mPOP,kNormal,argRegCX,argNone
mPOP,kNormal,argRegDX,argNone
mPOP,kNormal,argRegBX,argNone
mPOP,kNormal,argRegSP,argNone
mPOP,kNormal,argRegBP,argNone
mPOP,kNormal,argRegSI,argNone
mPOP,kNormal,argRegDI,argNone
0,kNormal,argNone,argNone
0,kNormal,argNone,argNone
0,kNormal,argNone,argNone
0,kNormal,argNone,argNone
0,kNormal,argNone,argNone
0,kNormal,argNone,argNone
0,kNormal,argNone,argNone
0,kNormal,argNone,argNone
0,kNormal,argNone,argNone
0,kNormal,argNone,argNone
0,kNormal,argNone,argNone
0,kNormal,argNone,argNone
0,kNormal,argNone,argNone
0,kNormal,argNone,argNone
0,kNormal,argNone,argNone
0,kNormal,argNone,argNone
mJO,kNormal,argShort,argNone
mJNO,kNormal,argShort,argNone
mJB,kNormal,argShort,argNone
mJAE,kNormal,argShort,argNone
mJZ,kNormal,argShort,argNone
mJNZ,kNormal,argShort,argNone
mJBE,kNormal,argShort,argNone
mJA,kNormal,argShort,argNone
mJS,kNormal,argShort,argNone
mJNS,kNormal,argShort,argNone
mJPE,kNormal,argShort,argNone
mJPO,kNormal,argShort,argNone
mJL,kNormal,argShort,argNone
mJGE,kNormal,argShort,argNone
mJLE,kNormal,argShort,argNone
mJG,kNormal,argShort,argNone
0,kArOp,argRegMem8,argImm8
0,kArOp,argRegMem16,argImm16
0,kNormal,argNone,argNone
0,kArOp,argRegMem16,argSImm8
mTEST,kNormal,argRegMem8,argReg8
mTEST,kNormal,argRegMem16,argReg16
mXCHG,kNormal,argReg8,argRegMem8
mXCHG,kNormal,argReg16,argRegMem16
mMOV,kNormal,argRegMem8,argReg8
mMOV,kNormal,argRegMem16,argReg16
mMOV,kNormal,argReg8,argRegMem8
mMOV,kNormal,argReg16,argRegMem16
mMOV,kNormal,argRegMem16,argSegReg
mLEA,kNormal,argReg16,argMem8
mMOV,kNormal,argSegReg,argRegMem16
mPOP,kNormal,argRegMem16,argNone
mNOP,kNormal,argNone,argNone
mXCHG,kNormal,argRegAX,argRegCX
mXCHG,kNormal,argRegAX,argRegDX
mXCHG,kNormal,argRegAX,argRegBX
mXCHG,kNormal,argRegAX,argRegSP
mXCHG,kNormal,argRegAX,argRegBP
mXCHG,kNormal,argRegAX,argRegSI
mXCHG,kNormal,argRegAX,argRegDI
mCBW,kNormal,argNone,argNone
mCWD,kNormal,argNone,argNone
mCALL,kNormal,argFar,argNone
mWAIT,kNormal,argNone,argNone
mPUSHF,kNormal,argNone,argNone
mPOPF,kNormal,argNone,argNone
mSAHF,kNormal,argNone,argNone
mLAHF,kNormal,argNone,argNone
mMOV,kNormal,argRegAL,argMemOffs8
mMOV,kNormal,argRegAX,argMemOffs16
mMOV,kNormal,argMemOffs8,argRegAL
mMOV,kNormal,argMemOffs16,argRegAX
mMOVSB,kNormal,argNone,argNone
mMOVSW,kNormal,argNone,argNone
mCMPSB,kNormal,argNone,argNone
mCMPSW,kNormal,argNone,argNone
mTEST,kNormal,argRegAL,argImm8
mTEST,kNormal,argRegAX,argImm16
mSTOSB,kNormal,argNone,argNone
mSTOSW,kNormal,argNone,argNone
mLODSB,kNormal,argNone,argNone
mLODSW,kNormal,argNone,argNone
mSCASB,kNormal,argNone,argNone
mSCASW,kNormal,argNone,argNone
mMOV,kNormal,argRegAL,argImm8
mMOV,kNormal,argRegCL,argImm8
mMOV,kNormal,argRegDL,argImm8
mMOV,kNormal,argRegBL,argImm8
mMOV,kNormal,argRegAH,argImm8
mMOV,kNormal,argRegCH,argImm8
mMOV,kNormal,argRegDH,argImm8
mMOV,kNormal,argRegBH,argImm8
mMOV,kNormal,argRegAX,argImm16
mMOV,kNormal,argRegCX,argImm16
mMOV,kNormal,argRegDX,argImm16
mMOV,kNormal,argRegBX,argImm16
mMOV,kNormal,argRegSP,argImm16
mMOV,kNormal,argRegBP,argImm16
mMOV,kNormal,argRegSI,argImm16
mMOV,kNormal,argRegDI,argImm16
0,kNormal,argNone,argNone
0,kNormal,argNone,argNone
mRETN,kNormal,argImm16,argNone
mRETN,kNormal,argNone,argNone
mLES,kNormal,argReg16,argMem32
mLDS,kNormal,argReg16,argMem32
mMOV,kNormal,argMem8,argImm8
mMOV,kNormal,argMem16,argImm16
0,kNormal,argNone,argNone
0,kNormal,argNone,argNone
mRETF,kNormal,argImm16,argNone
mRETF,kNormal,argNone,argNone
mINT,kNormal,argConst3,argNone
mINT,kNormal,argImm8,argNone
mINTO,kNormal,argNone,argNone
mIRET,kNormal,argNone,argNone
0,kShfOp,argRegMem8,argConst1
0,kShfOp,argRegMem16,argConst1
0,kShfOp,argRegMem8,argRegCL
0,kShfOp,argRegMem16,argRegCL
mAAM,kNormal,argImm8,argNone
mAAD,kNormal,argImm8,argNone
0,kNormal,argNone,argNone
mXLAT,kNormal,argNone,argNone
0,kNormal,argNone,argNone
0,kNormal,argNone,argNone
0,kNormal,argNone,argNone
0,kNormal,argNone,argNone
0,kNormal,argNone,argNone
0,kNormal,argNone,argNone
0,kNormal,argNone,argNone
0,kNormal,argNone,argNone
mLOOPNZ,kNormal,argShort,argNone
mLOOPZ,kNormal,argShort,argNone
mLOOP,kNormal,argShort,argNone
mJCXZ,kNormal,argShort,argNone
mIN,kNormal,argRegAL,argImm8
mIN,kNormal,argRegAX,argImm8
mOUT,kNormal,argImm8,argRegAL
mOUT,kNormal,argImm8,argRegAX
mCALL,kNormal,argNear,argNone
mJMP,kNormal,argNear,argNone
mJMP,kNormal,argFar,argNone
mJMP,kNormal,argShort,argNone
mIN,kNormal,argRegAL,argRegDX
mIN,kNormal,argRegAX,argRegDX
mOUT,kNormal,argRegDX,argRegAL
mOUT,kNormal,argRegDX,argRegAX
mLOCK,kPrefix,argNone,argNone
0,kNormal,argNone,argNone
mREPNE,kPrefix,argNone,argNone
mREP,kPrefix,argNone,argNone
mHLT,kNormal,argNone,argNone
mCMC,kNormal,argNone,argNone
0,kGrp1,argRegMem8,argNone
0,kGrp1,argRegMem16,argNone
mCLC,kNormal,argNone,argNone
mSTC,kNormal,argNone,argNone
mCLI,kNormal,argNone,argNone
mSTI,kNormal,argNone,argNone
mCLD,kNormal,argNone,argNone
mSTD,kNormal,argNone,argNone
0,kGrp2,argRegMem8,argNone
0,kGrp3,argRegMem16,argNone
