opcodeSize equ 3
	
opcodes db mADD, argRegMem8, argReg8 ;00
db mADD, argRegMem16, argReg16 ;01
db mADD, argReg8, argRegMem8 ;02
db mADD, argReg16, argRegMem16 ;03
db mADD, argAL, argImm8 ;04
db mADD, argAX, argImm16 ;05
db mPUSH, argES, argNone ;06
db mPOP, argES, argNone ;07
db mOR, argRegMem8, argReg8 ;08
db mOR, argRegMem16, argReg16 ;09
db mOR, argReg8, argRegMem8 ;0A
db mOR, argReg16, argRegMem16 ;0B
db mOR, argAL, argImm8 ;0C
db mOR, argAX, argImm16 ;0D
db mPUSH, argCS, argNone ;0E
db mUNKNOWN, argNone, argNone ;0F (not used!)
db mADC, argRegMem8, argReg8 ;10
db mADC, argRegMem16, argReg16 ;11
db mADC, argReg8, argRegMem8 ;12
db mADC, argReg16, argRegMem16 ;13
db mADC, argImm8, argNone ;14
db mADC, argImm16, argNone ;15
db mPUSH, argSS, argNone ;16
db mPOP, argSS, argNone ;17
db mSBB, argRegMem8, argReg8 ;18
db mSBB, argRegMem16, argReg16 ;19
db mSBB, argReg8, argRegMem8 ;1A
db mSBB, argReg16, argRegMem16 ;1B
db mSBB, argAL, argImm8 ;1C
db mSBB, argAX, argImm16 ;1D
db mPUSH, argDS, argNone ;1E
db mPUSH, argDS, argNone ;1F
db mAND, argRegMem8, argReg8 ;20
db mAND, argRegMem16, argReg16 ;21
db mAND, argReg8, argRegMem8 ;22
db mAND, argReg16, argRegMem16 ;23
db mAND, argAL, argImm8 ;24
db mAND, argAX, argImm16 ;25
db mSREGES, argNone, argNone ;26
db mDAA, argNone, argNone ;27
db mSUB, argRegMem8, argReg8 ;28
db mSUB, argRegMem16, argReg16 ;29
db mSUB, argReg8, argRegMem8 ;2A
db mSUB, argReg16, argRegMem16 ;2B
db mSUB, argAL, argImm8 ;2C
db mSUB, argAX, argImm16 ;2D
db mSREGCS, argNone, argNone ;2E
db mDAS, argNone, argNone ;2F
db mXOR, argRegMem8, argReg8 ;30
db mXOR, argRegMem16, argReg16 ;31
db mXOR, argReg8, argRegMem8 ;32
db mXOR, argReg16, argRegMem16 ;33
db mXOR, argAL, argImm8 ;34
db mXOR, argAX, argImm16 ;35
db mSREGSS, argNone, argNone ;36
db mAAA, argNone, argNone ;37
db mCMP, argRegMem8, argReg8 ;38
db mCMP, argRegMem16, argReg16 ;39
db mCMP, argReg8, argRegMem8 ;3A
db mCMP, argReg16, argRegMem16 ;3B
db mCMP, argAL, argImm8 ;3C
db mCMP, argAX, argImm16 ;3D
db mSREGDS, argNone, argNone ;3E
db mAAS, argNone, argNone ;3F
db mINC, argAX, argNone ;40
db mINC, argCX, argNone ;41
db mINC, argDX, argNone ;42
db mINC, argBX, argNone ;43
db mINC, argSP, argNone ;44
db mINC, argBP, argNone ;45
db mINC, argSI, argNone ;46
db mINC, argDI, argNone ;47
db mDEC, argAX, argNone ;48
db mDEC, argCX, argNone ;49
db mDEC, argDX, argNone ;4A
db mDEC, argBX, argNone ;4B
db mDEC, argSP, argNone ;4C
db mDEC, argBP, argNone ;4D
db mDEC, argSI, argNone ;4E
db mDEC, argDI, argNone ;4F
db mPUSH, argAX, argNone ;50
db mPUSH, argCX, argNone ;51
db mPUSH, argDX, argNone ;52
db mPUSH, argBX, argNone ;53
db mPUSH, argSP, argNone ;54
db mPUSH, argBP, argNone ;55
db mPUSH, argSI, argNone ;56
db mPUSH, argDI, argNone ;57
db mPOP, argAX, argNone ;58
db mPOP, argCX, argNone ;59
db mPOP, argDX, argNone ;5A
db mPOP, argBX, argNone ;5B
db mPOP, argSP, argNone ;5C
db mPOP, argBP, argNone ;5D
db mPOP, argSI, argNone ;5E
db mPOP, argDI, argNone ;5F
db mUNKNOWN, argNone, argNone ;60
db mUNKNOWN, argNone, argNone ;61
db mUNKNOWN, argNone, argNone ;62
db mUNKNOWN, argNone, argNone ;63
db mUNKNOWN, argNone, argNone ;64
db mUNKNOWN, argNone, argNone ;65
db mUNKNOWN, argNone, argNone ;66
db mUNKNOWN, argNone, argNone ;67
db mUNKNOWN, argNone, argNone ;68
db mUNKNOWN, argNone, argNone ;69
db mUNKNOWN, argNone, argNone ;6A
db mUNKNOWN, argNone, argNone ;6B
db mUNKNOWN, argNone, argNone ;6C
db mUNKNOWN, argNone, argNone ;6D
db mUNKNOWN, argNone, argNone ;6E
db mUNKNOWN, argNone, argNone ;6F
db mJO, argShort, argNone ;70
db mJNO, argShort, argNone ;71
db mJB, argShort, argNone ;72
db mJAE, argShort, argNone ;73
db mJE, argShort, argNone ;74
db mJNE, argShort, argNone ;75
db mJBE, argShort, argNone ;76
db mJA, argShort, argNone ;77
db mJS, argShort, argNone ;78
db mJNS, argShort, argNone ;79
db mJP, argShort, argNone ;7A
db mJNP, argShort, argNone ;7B
db mJL, argShort, argNone ;7C
db mJGE, argShort, argNone ;7D
db mJLE, argShort, argNone ;7E
db mJG, argShort, argNone ;7F
db g1, argRegMem8, argImm8 ;80
db g1, argRegMem16, argImm16 ;81
db mUNKNOWN, argNone, argNone ;82
db g1, argRegMem16, argImm8 ;83
db mTEST, argRegMem8, argReg8 ;84
db mTEST, argRegMem16, argReg16 ;85
db mXCHG, argReg8, argRegMem8 ;86
db mXCHG, argReg16, argRegMem16 ;87
db mMOV, argRegMem8, argReg8 ;88
db mMOV, argRegMem16, argReg16 ;89
db mMOV, argReg8, argRegMem8 ;8A
db mMOV, argReg16, argRegMem16 ;8B
db mMOV, argRegMem16, argSegReg ;8C
db mLEA, argReg16, argMem16 ;8D
db mMOV, argSegReg, argRegMem16 ;8E
db mPOP, argRegMem16, argNone ;8F
db mNOP, argNone, argNone ;90
db mXCHG, argAX, argCX ;91
db mXCHG, argAX, argDX ;92
db mXCHG, argAX, argBX ;93
db mXCHG, argAX, argSP ;94
db mXCHG, argAX, argBP ;95
db mXCHG, argAX, argSI ;96
db mXCHG, argAX, argDI ;97
db mCBW, argNone, argNone ;98
db mCWD, argNone, argNone ;99
db mCALL, argFar, argNone ;9A
db mWAIT, argNone, argNone ;9B
db mPUSHF, argNone, argNone ;9C
db mPOPF, argNone, argNone ;9D
db mSAHF, argNone, argNone ;9E
db mLAHF, argNone, argNone ;9F
db mMOV, argAL, argMemDirect8 ;A0
db mMOV, argAX, argMemDirect16 ;A1
db mMOV, argMemDirect8, argAL ;A2
db mMOV, argMemDirect16, argAX ;A3
db mMOVSB, argNone, argNone ;A4
db mMOVSW, argNone, argNone ;A5
db mCMPSB, argNone, argNone ;A6
db mCMPSW, argNone, argNone ;A7
db mTEST, argAL, argImm8 ;A8
db mTEST, argAX, argImm16 ;A9
db mSTOSB, argNone, argNone ;AA
db mSTOSW, argNone, argNone ;AB
db mLODSB, argNone, argNone ;AC
db mLODSW, argNone, argNone ;AD
db mSCASB, argNone, argNone ;AE
db mSCASW, argNone, argNone ;AF
db mMOV, argAL, argImm8 ;B0
db mMOV, argCL, argImm8 ;B1
db mMOV, argDL, argImm8 ;B2
db mMOV, argBL, argImm8 ;B3
db mMOV, argAH, argImm8 ;B4
db mMOV, argCH, argImm8 ;B5
db mMOV, argDH, argImm8 ;B6
db mMOV, argBH, argImm8 ;B7
db mMOV, argAX, argImm16 ;B8
db mMOV, argCX, argImm16 ;B9
db mMOV, argDX, argImm16 ;BA
db mMOV, argBX, argImm16 ;BB
db mMOV, argSP, argImm16 ;BC
db mMOV, argBP, argImm16 ;BD
db mMOV, argSI, argImm16 ;BE
db mMOV, argDI, argImm16 ;BF
db mUNKNOWN, argNone, argNone ;C0
db mUNKNOWN, argNone, argNone ;C1
db mRET, argImm16, argNone ;C2
db mRET, argNone, argNone ;C3
db mLES, argReg16, argMem16 ;C4
db mLDS, argReg16, argMem16 ;C5
db mMOV, argMem8, argImm8 ;C6
db mMOV, argMem16, argImm16 ;C7
db mUNKNOWN, argNone, argNone ;C8
db mUNKNOWN, argNone, argNone ;C9
db mRET, argImm16, argNone ;CA
db mRET, argNone, argNone ;CB
db mINT, arg3, argNone ;CC
db mINT, argImm8, argNone ;CD
db mINTO, argNone, argNone ;CE
db mIRET, argNone, argNone ;CF
db g2, argRegMem8, arg1 ;D0
db g2, argRegMem16, arg1 ;D1
db g2, argRegMem8, argCL ;D2
db g2, argRegMem16, argCL ;D3
db mAAM, argNone, argNone ;D4
db mAAD, argNone, argNone ;D5
db mUNKNOWN, argNone, argNone ;D6
db mXLAT, argNone, argNone ;D7
db mUNKNOWN, argNone, argNone ;D8
db mUNKNOWN, argNone, argNone ;D9
db mUNKNOWN, argNone, argNone ;DA
db mUNKNOWN, argNone, argNone ;DB
db mUNKNOWN, argNone, argNone ;DC
db mUNKNOWN, argNone, argNone ;DD
db mUNKNOWN, argNone, argNone ;DE
db mUNKNOWN, argNone, argNone ;DF
db mLOOPNE, argShort, argNone ;E0
db mLOOPE, argShort, argNone ;E1
db mLOOP, argShort, argNone ;E2
db mJCXZ, argShort, argNone ;E3
db mIN, argAL, argImm8 ;E4
db mIN, argAX, argImm8 ;E5
db mOUT, argAL, argImm8 ;E6
db mOUT, argAX, argImm8 ;E7
db mCALL, argNear, argNone ;E8
db mJMP, argNear, argNone ;E9
db mJMP, argFar, argNone ;EA
db mJMP, argShort, argNone ;EB
db mIN, argAL, argDX ;EC
db mIN, argAX, argDX ;ED
db mOUT, argAL, argDX ;EE
db mOUT, argAX, argDX ;EF
db mLOCK, argNone, argNone ;F0
db mUNKNOWN, argNone, argNone ;F1
db mREPNE, argNone, argNone ;F2
db mREP, argNone, argNone ;F3
db mHLT, argNone, argNone ;F4
db mCMC, argNone, argNone ;F5
db g3, argRegMem8, argNone ;F6
db g3, argRegMem16, argNone ;F7
db mCLC, argNone, argNone ;F8
db mSTC, argNone, argNone ;F9
db mCLI, argNone, argNone ;FA
db mSTI, argNone, argNone ;FB
db mCLD, argNone, argNone ;FC
db mSTD, argNone, argNone ;FD
db g4, argRegMem8, argNone ;FE
db g4, argRegMem16, argNone ;FF
