mtMOV db 'MOV$'
mtPUSH db 'PUSH$'
mtPOP db 'POP$'
mtXCHG db 'XCHG$'
mtOUT db 'OUT$'
mtIN db 'IN$'
mtXLAT db 'XLAT$'
mtLEA db 'LEA$'
mtLDS db 'LDS$'
mtLES db 'LES$'
mtLAHF db 'LAHF$'
mtSAHF db 'SAHF$'
mtPUSHF db 'PUSHF$'
mtPOPF db 'POPF$'
mtADD db 'ADD$'
mtADC db 'ADC$'
mtINC db 'INC$'
mtSUB db 'SUB$'
mtSBB db 'SBB$'
mtDEC db 'DEC$'
mtCMP db 'CMP$'
mtMUL db 'MUL$'
mtIMUL db 'IMUL$'
mtDIV db 'DIV$'
mtIDIV db 'IDIV$'
mtNEG db 'NEG$'
mtAAA db 'AAA$'
mtDAA db 'DAA$'
mtAAS db 'AAS$'
mtDAS db 'DAS$'
mtAAM db 'AAM$'
mtAAD db 'AAD$'
mtCBW db 'CBW$'
mtCWD db 'CWD$'
mtNOT db 'NOT$'
mtSHL db 'SHL$'
mtSHR db 'SHR$'
mtSAR db 'SAR$'
mtROL db 'ROL$'
mtROR db 'ROR$'
mtRCL db 'RCL$'
mtRCR db 'RCR$'
mtAND db 'AND$'
mtOR db 'OR$'
mtXOR db 'XOR$'
mtTEST db 'TEST$'
mtCLC db 'CLC$'
mtSTC db 'STC$'
mtCLI db 'CLI$'
mtSTI db 'STI$'
mtCLD db 'CLD$'
mtSTD db 'STD$'
mtSREGES db 'SREGES$'
mtSREGCS db 'SREGCS$'
mtSREGSS db 'SREGSS$'
mtSREGDS db 'SREGDS$'
mtREP db 'REP$'
mtREPNE db 'REPNE$'
mtNOP db 'NOP$'
mtWAIT db 'WAIT$'
mtJO db 'JO$'
mtJNO db 'JNO$'
mtJB db 'JB$'
mtJAE db 'JAE$'
mtJE db 'JE$'
mtJNE db 'JNE$'
mtJBE db 'JBE$'
mtJA db 'JA$'
mtJS db 'JS$'
mtJNS db 'JNS$'
mtJP db 'JP$'
mtJNP db 'JNP$'
mtJL db 'JL$'
mtJGE db 'JGE$'
mtJLE db 'JLE$'
mtJG db 'JG$'
mtMOVSB db 'MOVSB$'
mtMOVSW db 'MOVSW$'
mtCMPSB db 'CMPSB$'
mtCMPSW db 'CMPSW$'
mtSTOSB db 'STOSB$'
mtSTOSW db 'STOSW$'
mtLODSB db 'LODSB$'
mtLODSW db 'LODSW$'
mtSCASB db 'SCASB$'
mtSCASW db 'SCASW$'
mtINT db 'INT$'
mtINTO db 'INTO$'
mtIRET db 'IRET$'
mtLOOPNE db 'LOOPNE$'
mtLOOPE db 'LOOPE$'
mtLOOP db 'LOOP$'
mtJCXZ db 'JCXZ$'
mtCALL db 'CALL$'
mtLOCK db 'LOCK$'
mtHLT db 'HLT$'
mtCMC db 'CMC$'
mtRET db 'RET$'
mtSBC db 'SBC$'
mtJMP db 'JMP$'

mnemonics dw mtMOV, mtPUSH, mtPOP, mtXCHG, mtOUT, mtIN, mtXLAT, mtLEA, mtLDS, mtLES, mtLAHF, mtSAHF, mtPUSHF, mtPOPF, mtADD, mtADC, mtINC, mtSUB, mtSBB, mtDEC, mtCMP, mtMUL, mtIMUL, mtDIV, mtIDIV, mtNEG, mtAAA, mtDAA, mtAAS, mtDAS, mtAAM, mtAAD, mtCBW, mtCWD, mtNOT, mtSHL, mtSHR, mtSAR, mtROL, mtROR, mtRCL, mtRCR, mtAND, mtOR, mtXOR, mtTEST, mtCLC, mtSTC, mtCLI, mtSTI, mtCLD, mtSTD, mtSREGES, mtSREGCS, mtSREGSS, mtSREGDS, mtREP, mtREPNE, mtNOP, mtWAIT, mtJO, mtJNO, mtJB, mtJAE, mtJE, mtJNE, mtJBE, mtJA, mtJS, mtJNS, mtJP, mtJNP, mtJL, mtJGE, mtJLE, mtJG, mtMOVSB, mtMOVSW, mtCMPSB, mtCMPSW, mtSTOSB, mtSTOSW, mtLODSB, mtLODSW, mtSCASB, mtSCASW, mtINT, mtINTO, mtIRET, mtLOOPNE, mtLOOPE, mtLOOP, mtJCXZ, mtCALL, mtLOCK, mtHLT, mtCMC, mtRET, mtSBC, mtJMP

mUNKNOWN equ 0
mMOV equ 1
mPUSH equ 2
mPOP equ 3
mXCHG equ 4
mOUT equ 5
mIN equ 6
mXLAT equ 7
mLEA equ 8
mLDS equ 9
mLES equ 10
mLAHF equ 11
mSAHF equ 12
mPUSHF equ 13
mPOPF equ 14
mADD equ 15
mADC equ 16
mINC equ 17
mSUB equ 18
mSBB equ 19
mDEC equ 20
mCMP equ 21
mMUL equ 22
mIMUL equ 23
mDIV equ 24
mIDIV equ 25
mNEG equ 26
mAAA equ 27
mDAA equ 28
mAAS equ 29
mDAS equ 30
mAAM equ 31
mAAD equ 32
mCBW equ 33
mCWD equ 34
mNOT equ 35
mSHL equ 36
mSHR equ 37
mSAR equ 38
mROL equ 39
mROR equ 40
mRCL equ 41
mRCR equ 42
mAND equ 43
mOR equ 44
mXOR equ 45
mTEST equ 46
mCLC equ 47
mSTC equ 48
mCLI equ 49
mSTI equ 50
mCLD equ 51
mSTD equ 52
mSREGES equ 53
mSREGCS equ 54
mSREGSS equ 55
mSREGDS equ 56
mREP equ 57
mREPNE equ 58
mNOP equ 59
mWAIT equ 60
mJO equ 61
mJNO equ 62
mJB equ 63
mJAE equ 64
mJE equ 65
mJNE equ 66
mJBE equ 67
mJA equ 68
mJS equ 69
mJNS equ 70
mJP equ 71
mJNP equ 72
mJL equ 73
mJGE equ 74
mJLE equ 75
mJG equ 76
mMOVSB equ 77
mMOVSW equ 78
mCMPSB equ 79
mCMPSW equ 80
mSTOSB equ 81
mSTOSW equ 82
mLODSB equ 83
mLODSW equ 84
mSCASB equ 85
mSCASW equ 86
mINT equ 87
mINTO equ 88
mIRET equ 89
mLOOPNE equ 90
mLOOPE equ 91
mLOOP equ 92
mJCXZ equ 93
mCALL equ 94
mLOCK equ 95
mHLT equ 96
mCMC equ 97
mRET equ 98
mSBC equ 99
mJMP equ 100
