opcodes db mUNKNOWN, argNone, argNone, tNorm ;00
db mUNKNOWN, argNone, argNone, tNorm ;01
db mUNKNOWN, argNone, argNone, tNorm ;02
db mUNKNOWN, argNone, argNone, tNorm ;03
db mUNKNOWN, argNone, argNone, tNorm ;04
db mUNKNOWN, argNone, argNone, tNorm ;05
db mUNKNOWN, argNone, argNone, tNorm ;06
db mUNKNOWN, argNone, argNone, tNorm ;07
db mUNKNOWN, argNone, argNone, tNorm ;08
db mUNKNOWN, argNone, argNone, tNorm ;09
db mUNKNOWN, argNone, argNone, tNorm ;0A
db mUNKNOWN, argNone, argNone, tNorm ;0B
db mUNKNOWN, argNone, argNone, tNorm ;0C
db mUNKNOWN, argNone, argNone, tNorm ;0D
db mUNKNOWN, argNone, argNone, tNorm ;0E
db mUNKNOWN, argNone, argNone, tNorm ;0F
db mUNKNOWN, argNone, argNone, tNorm ;10
db mUNKNOWN, argNone, argNone, tNorm ;11
db mUNKNOWN, argNone, argNone, tNorm ;12
db mUNKNOWN, argNone, argNone, tNorm ;13
db mUNKNOWN, argNone, argNone, tNorm ;14
db mUNKNOWN, argNone, argNone, tNorm ;15
db mUNKNOWN, argNone, argNone, tNorm ;16
db mUNKNOWN, argNone, argNone, tNorm ;17
db mUNKNOWN, argNone, argNone, tNorm ;18
db mUNKNOWN, argNone, argNone, tNorm ;19
db mUNKNOWN, argNone, argNone, tNorm ;1A
db mUNKNOWN, argNone, argNone, tNorm ;1B
db mUNKNOWN, argNone, argNone, tNorm ;1C
db mUNKNOWN, argNone, argNone, tNorm ;1D
db mUNKNOWN, argNone, argNone, tNorm ;1E
db mUNKNOWN, argNone, argNone, tNorm ;1F
db mUNKNOWN, argNone, argNone, tNorm ;20
db mUNKNOWN, argNone, argNone, tNorm ;21
db mUNKNOWN, argNone, argNone, tNorm ;22
db mUNKNOWN, argNone, argNone, tNorm ;23
db mUNKNOWN, argNone, argNone, tNorm ;24
db mUNKNOWN, argNone, argNone, tNorm ;25
db mUNKNOWN, argNone, argNone, tNorm ;26
db mUNKNOWN, argNone, argNone, tNorm ;27
db mUNKNOWN, argNone, argNone, tNorm ;28
db mUNKNOWN, argNone, argNone, tNorm ;29
db mUNKNOWN, argNone, argNone, tNorm ;2A
db mUNKNOWN, argNone, argNone, tNorm ;2B
db mUNKNOWN, argNone, argNone, tNorm ;2C
db mUNKNOWN, argNone, argNone, tNorm ;2D
db mUNKNOWN, argNone, argNone, tNorm ;2E
db mUNKNOWN, argNone, argNone, tNorm ;2F
db mUNKNOWN, argNone, argNone, tNorm ;30
db mUNKNOWN, argNone, argNone, tNorm ;31
db mUNKNOWN, argNone, argNone, tNorm ;32
db mUNKNOWN, argNone, argNone, tNorm ;33
db mUNKNOWN, argNone, argNone, tNorm ;34
db mUNKNOWN, argNone, argNone, tNorm ;35
db mUNKNOWN, argNone, argNone, tNorm ;36
db mUNKNOWN, argNone, argNone, tNorm ;37
db mUNKNOWN, argNone, argNone, tNorm ;38
db mUNKNOWN, argNone, argNone, tNorm ;39
db mUNKNOWN, argNone, argNone, tNorm ;3A
db mUNKNOWN, argNone, argNone, tNorm ;3B
db mUNKNOWN, argNone, argNone, tNorm ;3C
db mUNKNOWN, argNone, argNone, tNorm ;3D
db mUNKNOWN, argNone, argNone, tNorm ;3E
db mUNKNOWN, argNone, argNone, tNorm ;3F
db mUNKNOWN, argNone, argNone, tNorm ;40
db mUNKNOWN, argNone, argNone, tNorm ;41
db mUNKNOWN, argNone, argNone, tNorm ;42
db mUNKNOWN, argNone, argNone, tNorm ;43
db mUNKNOWN, argNone, argNone, tNorm ;44
db mUNKNOWN, argNone, argNone, tNorm ;45
db mUNKNOWN, argNone, argNone, tNorm ;46
db mUNKNOWN, argNone, argNone, tNorm ;47
db mUNKNOWN, argNone, argNone, tNorm ;48
db mUNKNOWN, argNone, argNone, tNorm ;49
db mUNKNOWN, argNone, argNone, tNorm ;4A
db mUNKNOWN, argNone, argNone, tNorm ;4B
db mUNKNOWN, argNone, argNone, tNorm ;4C
db mUNKNOWN, argNone, argNone, tNorm ;4D
db mUNKNOWN, argNone, argNone, tNorm ;4E
db mUNKNOWN, argNone, argNone, tNorm ;4F
db mUNKNOWN, argNone, argNone, tNorm ;50
db mUNKNOWN, argNone, argNone, tNorm ;51
db mUNKNOWN, argNone, argNone, tNorm ;52
db mUNKNOWN, argNone, argNone, tNorm ;53
db mUNKNOWN, argNone, argNone, tNorm ;54
db mUNKNOWN, argNone, argNone, tNorm ;55
db mUNKNOWN, argNone, argNone, tNorm ;56
db mUNKNOWN, argNone, argNone, tNorm ;57
db mUNKNOWN, argNone, argNone, tNorm ;58
db mUNKNOWN, argNone, argNone, tNorm ;59
db mUNKNOWN, argNone, argNone, tNorm ;5A
db mUNKNOWN, argNone, argNone, tNorm ;5B
db mUNKNOWN, argNone, argNone, tNorm ;5C
db mUNKNOWN, argNone, argNone, tNorm ;5D
db mUNKNOWN, argNone, argNone, tNorm ;5E
db mUNKNOWN, argNone, argNone, tNorm ;5F
db mUNKNOWN, argNone, argNone, tNorm ;60
db mUNKNOWN, argNone, argNone, tNorm ;61
db mUNKNOWN, argNone, argNone, tNorm ;62
db mUNKNOWN, argNone, argNone, tNorm ;63
db mUNKNOWN, argNone, argNone, tNorm ;64
db mUNKNOWN, argNone, argNone, tNorm ;65
db mUNKNOWN, argNone, argNone, tNorm ;66
db mUNKNOWN, argNone, argNone, tNorm ;67
db mUNKNOWN, argNone, argNone, tNorm ;68
db mUNKNOWN, argNone, argNone, tNorm ;69
db mUNKNOWN, argNone, argNone, tNorm ;6A
db mUNKNOWN, argNone, argNone, tNorm ;6B
db mUNKNOWN, argNone, argNone, tNorm ;6C
db mUNKNOWN, argNone, argNone, tNorm ;6D
db mUNKNOWN, argNone, argNone, tNorm ;6E
db mUNKNOWN, argNone, argNone, tNorm ;6F
db mUNKNOWN, argNone, argNone, tNorm ;70
db mUNKNOWN, argNone, argNone, tNorm ;71
db mUNKNOWN, argNone, argNone, tNorm ;72
db mUNKNOWN, argNone, argNone, tNorm ;73
db mUNKNOWN, argNone, argNone, tNorm ;74
db mUNKNOWN, argNone, argNone, tNorm ;75
db mUNKNOWN, argNone, argNone, tNorm ;76
db mUNKNOWN, argNone, argNone, tNorm ;77
db mUNKNOWN, argNone, argNone, tNorm ;78
db mUNKNOWN, argNone, argNone, tNorm ;79
db mUNKNOWN, argNone, argNone, tNorm ;7A
db mUNKNOWN, argNone, argNone, tNorm ;7B
db mUNKNOWN, argNone, argNone, tNorm ;7C
db mUNKNOWN, argNone, argNone, tNorm ;7D
db mUNKNOWN, argNone, argNone, tNorm ;7E
db mUNKNOWN, argNone, argNone, tNorm ;7F
db mUNKNOWN, argNone, argNone, tNorm ;80
db mUNKNOWN, argNone, argNone, tNorm ;81
db mUNKNOWN, argNone, argNone, tNorm ;82
db mUNKNOWN, argNone, argNone, tNorm ;83
db mUNKNOWN, argNone, argNone, tNorm ;84
db mUNKNOWN, argNone, argNone, tNorm ;85
db mUNKNOWN, argNone, argNone, tNorm ;86
db mUNKNOWN, argNone, argNone, tNorm ;87
db mUNKNOWN, argNone, argNone, tNorm ;88
db mUNKNOWN, argNone, argNone, tNorm ;89
db mUNKNOWN, argNone, argNone, tNorm ;8A
db mUNKNOWN, argNone, argNone, tNorm ;8B
db mUNKNOWN, argNone, argNone, tNorm ;8C
db mUNKNOWN, argNone, argNone, tNorm ;8D
db mUNKNOWN, argNone, argNone, tNorm ;8E
db mUNKNOWN, argNone, argNone, tNorm ;8F
db mUNKNOWN, argNone, argNone, tNorm ;90
db mUNKNOWN, argNone, argNone, tNorm ;91
db mUNKNOWN, argNone, argNone, tNorm ;92
db mUNKNOWN, argNone, argNone, tNorm ;93
db mUNKNOWN, argNone, argNone, tNorm ;94
db mUNKNOWN, argNone, argNone, tNorm ;95
db mUNKNOWN, argNone, argNone, tNorm ;96
db mUNKNOWN, argNone, argNone, tNorm ;97
db mUNKNOWN, argNone, argNone, tNorm ;98
db mUNKNOWN, argNone, argNone, tNorm ;99
db mUNKNOWN, argNone, argNone, tNorm ;9A
db mUNKNOWN, argNone, argNone, tNorm ;9B
db mUNKNOWN, argNone, argNone, tNorm ;9C
db mUNKNOWN, argNone, argNone, tNorm ;9D
db mUNKNOWN, argNone, argNone, tNorm ;9E
db mUNKNOWN, argNone, argNone, tNorm ;9F
db mUNKNOWN, argNone, argNone, tNorm ;A0
db mUNKNOWN, argNone, argNone, tNorm ;A1
db mUNKNOWN, argNone, argNone, tNorm ;A2
db mUNKNOWN, argNone, argNone, tNorm ;A3
db mUNKNOWN, argNone, argNone, tNorm ;A4
db mUNKNOWN, argNone, argNone, tNorm ;A5
db mUNKNOWN, argNone, argNone, tNorm ;A6
db mUNKNOWN, argNone, argNone, tNorm ;A7
db mUNKNOWN, argNone, argNone, tNorm ;A8
db mUNKNOWN, argNone, argNone, tNorm ;A9
db mUNKNOWN, argNone, argNone, tNorm ;AA
db mUNKNOWN, argNone, argNone, tNorm ;AB
db mUNKNOWN, argNone, argNone, tNorm ;AC
db mUNKNOWN, argNone, argNone, tNorm ;AD
db mUNKNOWN, argNone, argNone, tNorm ;AE
db mUNKNOWN, argNone, argNone, tNorm ;AF
db mUNKNOWN, argNone, argNone, tNorm ;B0
db mUNKNOWN, argNone, argNone, tNorm ;B1
db mUNKNOWN, argNone, argNone, tNorm ;B2
db mUNKNOWN, argNone, argNone, tNorm ;B3
db mUNKNOWN, argNone, argNone, tNorm ;B4
db mUNKNOWN, argNone, argNone, tNorm ;B5
db mUNKNOWN, argNone, argNone, tNorm ;B6
db mUNKNOWN, argNone, argNone, tNorm ;B7
db mUNKNOWN, argNone, argNone, tNorm ;B8
db mUNKNOWN, argNone, argNone, tNorm ;B9
db mUNKNOWN, argNone, argNone, tNorm ;BA
db mUNKNOWN, argNone, argNone, tNorm ;BB
db mUNKNOWN, argNone, argNone, tNorm ;BC
db mUNKNOWN, argNone, argNone, tNorm ;BD
db mUNKNOWN, argNone, argNone, tNorm ;BE
db mUNKNOWN, argNone, argNone, tNorm ;BF
db mUNKNOWN, argNone, argNone, tNorm ;C0
db mUNKNOWN, argNone, argNone, tNorm ;C1
db mUNKNOWN, argNone, argNone, tNorm ;C2
db mUNKNOWN, argNone, argNone, tNorm ;C3
db mUNKNOWN, argNone, argNone, tNorm ;C4
db mUNKNOWN, argNone, argNone, tNorm ;C5
db mUNKNOWN, argNone, argNone, tNorm ;C6
db mUNKNOWN, argNone, argNone, tNorm ;C7
db mUNKNOWN, argNone, argNone, tNorm ;C8
db mUNKNOWN, argNone, argNone, tNorm ;C9
db mUNKNOWN, argNone, argNone, tNorm ;CA
db mUNKNOWN, argNone, argNone, tNorm ;CB
db mUNKNOWN, argNone, argNone, tNorm ;CC
db mUNKNOWN, argNone, argNone, tNorm ;CD
db mUNKNOWN, argNone, argNone, tNorm ;CE
db mUNKNOWN, argNone, argNone, tNorm ;CF
db mUNKNOWN, argNone, argNone, tNorm ;D0
db mUNKNOWN, argNone, argNone, tNorm ;D1
db mUNKNOWN, argNone, argNone, tNorm ;D2
db mUNKNOWN, argNone, argNone, tNorm ;D3
db mUNKNOWN, argNone, argNone, tNorm ;D4
db mUNKNOWN, argNone, argNone, tNorm ;D5
db mUNKNOWN, argNone, argNone, tNorm ;D6
db mUNKNOWN, argNone, argNone, tNorm ;D7
db mUNKNOWN, argNone, argNone, tNorm ;D8
db mUNKNOWN, argNone, argNone, tNorm ;D9
db mUNKNOWN, argNone, argNone, tNorm ;DA
db mUNKNOWN, argNone, argNone, tNorm ;DB
db mUNKNOWN, argNone, argNone, tNorm ;DC
db mUNKNOWN, argNone, argNone, tNorm ;DD
db mUNKNOWN, argNone, argNone, tNorm ;DE
db mUNKNOWN, argNone, argNone, tNorm ;DF
db mUNKNOWN, argNone, argNone, tNorm ;E0
db mUNKNOWN, argNone, argNone, tNorm ;E1
db mUNKNOWN, argNone, argNone, tNorm ;E2
db mUNKNOWN, argNone, argNone, tNorm ;E3
db mUNKNOWN, argNone, argNone, tNorm ;E4
db mUNKNOWN, argNone, argNone, tNorm ;E5
db mUNKNOWN, argNone, argNone, tNorm ;E6
db mUNKNOWN, argNone, argNone, tNorm ;E7
db mUNKNOWN, argNone, argNone, tNorm ;E8
db mUNKNOWN, argNone, argNone, tNorm ;E9
db mUNKNOWN, argNone, argNone, tNorm ;EA
db mUNKNOWN, argNone, argNone, tNorm ;EB
db mUNKNOWN, argNone, argNone, tNorm ;EC
db mUNKNOWN, argNone, argNone, tNorm ;ED
db mUNKNOWN, argNone, argNone, tNorm ;EE
db mUNKNOWN, argNone, argNone, tNorm ;EF
db mUNKNOWN, argNone, argNone, tNorm ;F0
db mUNKNOWN, argNone, argNone, tNorm ;F1
db mUNKNOWN, argNone, argNone, tNorm ;F2
db mUNKNOWN, argNone, argNone, tNorm ;F3
db mUNKNOWN, argNone, argNone, tNorm ;F4
db mUNKNOWN, argNone, argNone, tNorm ;F5
db mUNKNOWN, argNone, argNone, tNorm ;F6
db mUNKNOWN, argNone, argNone, tNorm ;F7
db mUNKNOWN, argNone, argNone, tNorm ;F8
db mUNKNOWN, argNone, argNone, tNorm ;F9
db mUNKNOWN, argNone, argNone, tNorm ;FA
db mUNKNOWN, argNone, argNone, tNorm ;FB
db mUNKNOWN, argNone, argNone, tNorm ;FC
db mUNKNOWN, argNone, argNone, tNorm ;FD
db mUNKNOWN, argNone, argNone, tNorm ;FE
db mUNKNOWN, argNone, argNone, tNorm ;FF
